/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uoDt6JhkDis
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function ChatPage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-background text-foreground">
      <div className="w-full max-w-md p-4 space-y-4">
        <form className="flex items-center gap-2">
          <Input
            type="text"
            placeholder="Enter your message"
            className="flex-1 rounded-md border border-input bg-background px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-1 focus:ring-primary"
          />
          <Button
            type="submit"
            className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary"
          >
            Submit
          </Button>
        </form>
        <div className="rounded-md border border-input bg-background p-4 text-sm shadow-sm">
          <p className="text-muted-foreground">Your response will be displayed here.</p>
        </div>
      </div>
    </div>
  )
}
